// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package services.energy;

public interface DevicesOffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.DevicesOffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceOff = 1;</code>
   */
  java.lang.String getDeviceOff();
  /**
   * <code>string deviceOff = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceOffBytes();
}
