// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package services.energy;

public interface LightAdjustRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.LightAdjustRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightId = 1;</code>
   */
  int getLightId();

  /**
   * <code>string adjust = 2;</code>
   */
  java.lang.String getAdjust();
  /**
   * <code>string adjust = 2;</code>
   */
  com.google.protobuf.ByteString
      getAdjustBytes();
}
