// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package services.energy;

public interface LightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.LightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightOn = 2;</code>
   */
  java.lang.String getLightOn();
  /**
   * <code>string lightOn = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightOnBytes();
}
