// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package services.energy;

public interface LightAdjustResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.LightAdjustResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string adjustMade = 1;</code>
   */
  java.lang.String getAdjustMade();
  /**
   * <code>string adjustMade = 1;</code>
   */
  com.google.protobuf.ByteString
      getAdjustMadeBytes();
}
