// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: climateControl.proto

package grpc.services.climate;

public final class ClimateServiceImpl {
  private ClimateServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_HVACStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_HVACStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_HVACStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_HVACStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_CoLevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_CoLevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_CoLevelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_CoLevelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024climateControl.proto\022\007climate\"#\n\021HVACS" +
      "tatusRequest\022\016\n\006HVACId\030\001 \001(\005\"$\n\022HVACStat" +
      "usResponse\022\016\n\006status\030\001 \001(\t\"2\n\013TempReques" +
      "t\022\016\n\006HVACId\030\001 \001(\005\022\023\n\013temperature\030\002 \001(\005\"\036" +
      "\n\014TempResponse\022\016\n\006status\030\001 \001(\t\"0\n\016CoLeve" +
      "lRequest\022\020\n\010building\030\001 \001(\t\022\014\n\004room\030\002 \001(\t" +
      "\"2\n\017CoLevelResponse\022\017\n\007Colevel\030\001 \001(\001\022\016\n\006" +
      "HVACId\030\002 \001(\t2\341\001\n\016ClimateService\022K\n\016showH" +
      "VACStatus\022\032.climate.HVACStatusRequest\032\033." +
      "climate.HVACStatusResponse\"\000\022>\n\013setHVACt" +
      "emp\022\024.climate.TempRequest\032\025.climate.Temp" +
      "Response\"\000(\001\022B\n\007checkCO\022\027.climate.CoLeve" +
      "lRequest\032\030.climate.CoLevelResponse\"\000(\0010\001" +
      "B-\n\025grpc.services.climateB\022ClimateServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_climate_HVACStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_climate_HVACStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_HVACStatusRequest_descriptor,
        new java.lang.String[] { "HVACId", });
    internal_static_climate_HVACStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_climate_HVACStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_HVACStatusResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_climate_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_climate_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_TempRequest_descriptor,
        new java.lang.String[] { "HVACId", "Temperature", });
    internal_static_climate_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_climate_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_TempResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_climate_CoLevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_climate_CoLevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_CoLevelRequest_descriptor,
        new java.lang.String[] { "Building", "Room", });
    internal_static_climate_CoLevelResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_climate_CoLevelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_CoLevelResponse_descriptor,
        new java.lang.String[] { "Colevel", "HVACId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
