// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: climateControl.proto

package grpc.services.climate;

public interface CoLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:climate.CoLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string building = 1;</code>
   */
  java.lang.String getBuilding();
  /**
   * <code>string building = 1;</code>
   */
  com.google.protobuf.ByteString
      getBuildingBytes();

  /**
   * <code>string room = 2;</code>
   */
  java.lang.String getRoom();
  /**
   * <code>string room = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomBytes();
}
