// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: climateControl.proto

package grpc.services.climate;

/**
 * Protobuf type {@code climate.ExtractionResponse}
 */
public  final class ExtractionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:climate.ExtractionResponse)
    ExtractionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExtractionResponse.newBuilder() to construct.
  private ExtractionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExtractionResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExtractionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.services.climate.CoLevel.Builder subBuilder = null;
            if (coLevel_ != null) {
              subBuilder = coLevel_.toBuilder();
            }
            coLevel_ = input.readMessage(grpc.services.climate.CoLevel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(coLevel_);
              coLevel_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.climate.ClimateServiceImpl.internal_static_climate_ExtractionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.climate.ClimateServiceImpl.internal_static_climate_ExtractionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.climate.ExtractionResponse.class, grpc.services.climate.ExtractionResponse.Builder.class);
  }

  public static final int COLEVEL_FIELD_NUMBER = 1;
  private grpc.services.climate.CoLevel coLevel_;
  /**
   * <code>.climate.CoLevel coLevel = 1;</code>
   */
  public boolean hasCoLevel() {
    return coLevel_ != null;
  }
  /**
   * <code>.climate.CoLevel coLevel = 1;</code>
   */
  public grpc.services.climate.CoLevel getCoLevel() {
    return coLevel_ == null ? grpc.services.climate.CoLevel.getDefaultInstance() : coLevel_;
  }
  /**
   * <code>.climate.CoLevel coLevel = 1;</code>
   */
  public grpc.services.climate.CoLevelOrBuilder getCoLevelOrBuilder() {
    return getCoLevel();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (coLevel_ != null) {
      output.writeMessage(1, getCoLevel());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (coLevel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCoLevel());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.climate.ExtractionResponse)) {
      return super.equals(obj);
    }
    grpc.services.climate.ExtractionResponse other = (grpc.services.climate.ExtractionResponse) obj;

    boolean result = true;
    result = result && (hasCoLevel() == other.hasCoLevel());
    if (hasCoLevel()) {
      result = result && getCoLevel()
          .equals(other.getCoLevel());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCoLevel()) {
      hash = (37 * hash) + COLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getCoLevel().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.climate.ExtractionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.climate.ExtractionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.climate.ExtractionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.climate.ExtractionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.climate.ExtractionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code climate.ExtractionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:climate.ExtractionResponse)
      grpc.services.climate.ExtractionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.climate.ClimateServiceImpl.internal_static_climate_ExtractionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.climate.ClimateServiceImpl.internal_static_climate_ExtractionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.climate.ExtractionResponse.class, grpc.services.climate.ExtractionResponse.Builder.class);
    }

    // Construct using grpc.services.climate.ExtractionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (coLevelBuilder_ == null) {
        coLevel_ = null;
      } else {
        coLevel_ = null;
        coLevelBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.climate.ClimateServiceImpl.internal_static_climate_ExtractionResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.climate.ExtractionResponse getDefaultInstanceForType() {
      return grpc.services.climate.ExtractionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.climate.ExtractionResponse build() {
      grpc.services.climate.ExtractionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.climate.ExtractionResponse buildPartial() {
      grpc.services.climate.ExtractionResponse result = new grpc.services.climate.ExtractionResponse(this);
      if (coLevelBuilder_ == null) {
        result.coLevel_ = coLevel_;
      } else {
        result.coLevel_ = coLevelBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.climate.ExtractionResponse) {
        return mergeFrom((grpc.services.climate.ExtractionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.climate.ExtractionResponse other) {
      if (other == grpc.services.climate.ExtractionResponse.getDefaultInstance()) return this;
      if (other.hasCoLevel()) {
        mergeCoLevel(other.getCoLevel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.climate.ExtractionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.climate.ExtractionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.services.climate.CoLevel coLevel_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.climate.CoLevel, grpc.services.climate.CoLevel.Builder, grpc.services.climate.CoLevelOrBuilder> coLevelBuilder_;
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public boolean hasCoLevel() {
      return coLevelBuilder_ != null || coLevel_ != null;
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public grpc.services.climate.CoLevel getCoLevel() {
      if (coLevelBuilder_ == null) {
        return coLevel_ == null ? grpc.services.climate.CoLevel.getDefaultInstance() : coLevel_;
      } else {
        return coLevelBuilder_.getMessage();
      }
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public Builder setCoLevel(grpc.services.climate.CoLevel value) {
      if (coLevelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coLevel_ = value;
        onChanged();
      } else {
        coLevelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public Builder setCoLevel(
        grpc.services.climate.CoLevel.Builder builderForValue) {
      if (coLevelBuilder_ == null) {
        coLevel_ = builderForValue.build();
        onChanged();
      } else {
        coLevelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public Builder mergeCoLevel(grpc.services.climate.CoLevel value) {
      if (coLevelBuilder_ == null) {
        if (coLevel_ != null) {
          coLevel_ =
            grpc.services.climate.CoLevel.newBuilder(coLevel_).mergeFrom(value).buildPartial();
        } else {
          coLevel_ = value;
        }
        onChanged();
      } else {
        coLevelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public Builder clearCoLevel() {
      if (coLevelBuilder_ == null) {
        coLevel_ = null;
        onChanged();
      } else {
        coLevel_ = null;
        coLevelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public grpc.services.climate.CoLevel.Builder getCoLevelBuilder() {
      
      onChanged();
      return getCoLevelFieldBuilder().getBuilder();
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    public grpc.services.climate.CoLevelOrBuilder getCoLevelOrBuilder() {
      if (coLevelBuilder_ != null) {
        return coLevelBuilder_.getMessageOrBuilder();
      } else {
        return coLevel_ == null ?
            grpc.services.climate.CoLevel.getDefaultInstance() : coLevel_;
      }
    }
    /**
     * <code>.climate.CoLevel coLevel = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.climate.CoLevel, grpc.services.climate.CoLevel.Builder, grpc.services.climate.CoLevelOrBuilder> 
        getCoLevelFieldBuilder() {
      if (coLevelBuilder_ == null) {
        coLevelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.services.climate.CoLevel, grpc.services.climate.CoLevel.Builder, grpc.services.climate.CoLevelOrBuilder>(
                getCoLevel(),
                getParentForChildren(),
                isClean());
        coLevel_ = null;
      }
      return coLevelBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:climate.ExtractionResponse)
  }

  // @@protoc_insertion_point(class_scope:climate.ExtractionResponse)
  private static final grpc.services.climate.ExtractionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.climate.ExtractionResponse();
  }

  public static grpc.services.climate.ExtractionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExtractionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExtractionResponse>() {
    @java.lang.Override
    public ExtractionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExtractionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExtractionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExtractionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.climate.ExtractionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

