// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: climateControl.proto

package grpc.services.climate;

public interface HvacResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:climate.HvacResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.climate.Hvac hvac = 1;</code>
   */
  boolean hasHvac();
  /**
   * <code>.climate.Hvac hvac = 1;</code>
   */
  grpc.services.climate.Hvac getHvac();
  /**
   * <code>.climate.Hvac hvac = 1;</code>
   */
  grpc.services.climate.HvacOrBuilder getHvacOrBuilder();
}
