// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: climateControl.proto

package grpc.services.climate;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:climate.TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 HVACId = 1;</code>
   */
  int getHVACId();

  /**
   * <code>int32 temperature = 2;</code>
   */
  int getTemperature();
}
