// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface DevicesOffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.DevicesOffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool deviceOff = 1;</code>
   */
  boolean getDeviceOff();
}
