// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface LightsOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.LightsOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightId = 1;</code>
   */
  int getLightId();
}
