// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface LightsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.Lights)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightId = 1;</code>
   */
  int getLightId();

  /**
   * <code>string lightStatus = 2;</code>
   */
  java.lang.String getLightStatus();
  /**
   * <code>string lightStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightStatusBytes();

  /**
   * <code>int32 adjust = 3;</code>
   */
  int getAdjust();
}
