// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface LightAdjustRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.LightAdjustRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightId = 1;</code>
   */
  int getLightId();

  /**
   * <code>int32 adjust = 2;</code>
   */
  int getAdjust();
}
