// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UtilityService.proto

package grpc.services.utility;

public interface CameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Utility.CameraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool camera = 1;</code>
   */
  boolean getCamera();
}
