// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Utility.proto

package grpc.services.utility;

public interface DevicesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Utility.DevicesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool devices = 1;</code>
   */
  boolean getDevices();
}
