// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UtilityService.proto

package grpc.services.utility;

public interface DevicesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Utility.DevicesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool devices = 1;</code>
   */
  boolean getDevices();
}
