// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UtilityService.proto

package grpc.services.utility;

public interface PrinterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Utility.PrinterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pList = 1;</code>
   */
  java.lang.String getPList();
  /**
   * <code>string pList = 1;</code>
   */
  com.google.protobuf.ByteString
      getPListBytes();
}
