// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Utility.proto

package grpc.services.utility;

public final class UtilityServiceImpl {
  private UtilityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utility_DevicesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utility_DevicesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utility_DevicesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utility_DevicesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utility_CameraRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utility_CameraRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utility_CameraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utility_CameraResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utility_PrinterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utility_PrinterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utility_PrinterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utility_PrinterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rUtility.proto\022\007Utility\"!\n\016DevicesReque" +
      "st\022\017\n\007devices\030\001 \001(\010\"\"\n\017DevicesResponse\022\017" +
      "\n\007devices\030\001 \001(\010\"\037\n\rCameraRequest\022\016\n\006came" +
      "ra\030\001 \001(\010\" \n\016CameraResponse\022\016\n\006camera\030\001 \001" +
      "(\010\"\037\n\016PrinterRequest\022\r\n\005pList\030\001 \001(\t\" \n\017P" +
      "rinterResponse\022\r\n\005pList\030\001 \001(\t2\341\001\n\016Utilit" +
      "yService\022D\n\rswitchDevices\022\027.Utility.Devi" +
      "cesRequest\032\030.Utility.DevicesResponse\"\000\022C" +
      "\n\016switchCameraOn\022\026.Utility.CameraRequest" +
      "\032\027.Utility.CameraResponse\"\000\022D\n\tprintList" +
      "\022\027.Utility.PrinterRequest\032\030.Utility.Prin" +
      "terResponse\"\000(\0010\001B-\n\025grpc.services.utili" +
      "tyB\022UtilityServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Utility_DevicesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Utility_DevicesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utility_DevicesRequest_descriptor,
        new java.lang.String[] { "Devices", });
    internal_static_Utility_DevicesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Utility_DevicesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utility_DevicesResponse_descriptor,
        new java.lang.String[] { "Devices", });
    internal_static_Utility_CameraRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Utility_CameraRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utility_CameraRequest_descriptor,
        new java.lang.String[] { "Camera", });
    internal_static_Utility_CameraResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Utility_CameraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utility_CameraResponse_descriptor,
        new java.lang.String[] { "Camera", });
    internal_static_Utility_PrinterRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Utility_PrinterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utility_PrinterRequest_descriptor,
        new java.lang.String[] { "PList", });
    internal_static_Utility_PrinterResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Utility_PrinterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utility_PrinterResponse_descriptor,
        new java.lang.String[] { "PList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
