// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personnelOccupancy.proto

package grpc.services.occupancy;

public interface CameraSwitchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.CameraSwitchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cameraId = 1;</code>
   */
  int getCameraId();
}
