// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personnelOccupancy.proto

package grpc.services.occupancy;

public interface CameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.CameraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cameraOn = 2;</code>
   */
  java.lang.String getCameraOn();
  /**
   * <code>string cameraOn = 2;</code>
   */
  com.google.protobuf.ByteString
      getCameraOnBytes();
}
