// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personnelOccupancy.proto

package grpc.services.occupancy;

public interface LocalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.LocalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room = 1;</code>
   */
  java.lang.String getRoom();
  /**
   * <code>string room = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomBytes();
}
