// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personnelOccupancy.proto

package grpc.services.occupancy;

public interface OccupancyLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.OccupancyLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 currtime = 1;</code>
   */
  long getCurrtime();

  /**
   * <code>int32 localOccupancy = 2;</code>
   */
  int getLocalOccupancy();
}
