// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personnelOccupancy.proto

package grpc.services.occupancy;

public interface OccupancyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.OccupancyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.occupancy.Personnel personnel = 1;</code>
   */
  boolean hasPersonnel();
  /**
   * <code>.occupancy.Personnel personnel = 1;</code>
   */
  grpc.services.occupancy.Personnel getPersonnel();
  /**
   * <code>.occupancy.Personnel personnel = 1;</code>
   */
  grpc.services.occupancy.PersonnelOrBuilder getPersonnelOrBuilder();
}
