// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personnelOccupancy.proto

package grpc.services.occupancy;

public final class OccupancyServiceImpl {
  private OccupancyServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_LocalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_LocalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_OccupancyLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_OccupancyLevel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_CameraSwitchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_CameraSwitchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_CameraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_CameraResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_VisitorsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_VisitorsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_VisitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_VisitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030personnelOccupancy.proto\022\toccupancy\".\n" +
      "\014LocalRequest\022\020\n\010building\030\001 \001(\t\022\014\n\004room\030" +
      "\002 \001(\t\":\n\016OccupancyLevel\022\020\n\010currtime\030\001 \001(" +
      "\003\022\026\n\016localOccupancy\030\002 \001(\005\"\'\n\023CameraSwitc" +
      "hRequest\022\020\n\010cameraId\030\001 \001(\005\"\"\n\016CameraResp" +
      "onse\022\020\n\010cameraOn\030\002 \001(\t\"#\n\017VisitorsReques" +
      "t\022\020\n\010building\030\001 \001(\t\"J\n\017VisitorResponse\022\020" +
      "\n\010building\030\001 \001(\t\022\020\n\010currtime\030\002 \001(\003\022\023\n\013vi" +
      "sitorList\030\003 \001(\t2\371\001\n\020OccupancyService\022H\n\014" +
      "getOccupancy\022\027.occupancy.LocalRequest\032\031." +
      "occupancy.OccupancyLevel\"\000(\0010\001\022M\n\016switch" +
      "CameraOn\022\036.occupancy.CameraSwitchRequest" +
      "\032\031.occupancy.CameraResponse\"\000\022L\n\016getVisi" +
      "torList\022\032.occupancy.VisitorsRequest\032\032.oc" +
      "cupancy.VisitorResponse\"\0000\001B1\n\027grpc.serv" +
      "ices.occupancyB\024OccupancyServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_occupancy_LocalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_occupancy_LocalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_LocalRequest_descriptor,
        new java.lang.String[] { "Building", "Room", });
    internal_static_occupancy_OccupancyLevel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_occupancy_OccupancyLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_OccupancyLevel_descriptor,
        new java.lang.String[] { "Currtime", "LocalOccupancy", });
    internal_static_occupancy_CameraSwitchRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_occupancy_CameraSwitchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_CameraSwitchRequest_descriptor,
        new java.lang.String[] { "CameraId", });
    internal_static_occupancy_CameraResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_occupancy_CameraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_CameraResponse_descriptor,
        new java.lang.String[] { "CameraOn", });
    internal_static_occupancy_VisitorsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_occupancy_VisitorsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_VisitorsRequest_descriptor,
        new java.lang.String[] { "Building", });
    internal_static_occupancy_VisitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_occupancy_VisitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_VisitorResponse_descriptor,
        new java.lang.String[] { "Building", "Currtime", "VisitorList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
