// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personnelOccupancy.proto

package grpc.services.occupancy;

/**
 * Protobuf type {@code occupancy.OccupancyLevel}
 */
public  final class OccupancyLevel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:occupancy.OccupancyLevel)
    OccupancyLevelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OccupancyLevel.newBuilder() to construct.
  private OccupancyLevel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OccupancyLevel() {
    currtime_ = 0L;
    localOccupancy_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OccupancyLevel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            currtime_ = input.readInt64();
            break;
          }
          case 16: {

            localOccupancy_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyLevel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyLevel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.occupancy.OccupancyLevel.class, grpc.services.occupancy.OccupancyLevel.Builder.class);
  }

  public static final int CURRTIME_FIELD_NUMBER = 1;
  private long currtime_;
  /**
   * <code>int64 currtime = 1;</code>
   */
  public long getCurrtime() {
    return currtime_;
  }

  public static final int LOCALOCCUPANCY_FIELD_NUMBER = 2;
  private int localOccupancy_;
  /**
   * <code>int32 localOccupancy = 2;</code>
   */
  public int getLocalOccupancy() {
    return localOccupancy_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currtime_ != 0L) {
      output.writeInt64(1, currtime_);
    }
    if (localOccupancy_ != 0) {
      output.writeInt32(2, localOccupancy_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currtime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, currtime_);
    }
    if (localOccupancy_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, localOccupancy_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.occupancy.OccupancyLevel)) {
      return super.equals(obj);
    }
    grpc.services.occupancy.OccupancyLevel other = (grpc.services.occupancy.OccupancyLevel) obj;

    boolean result = true;
    result = result && (getCurrtime()
        == other.getCurrtime());
    result = result && (getLocalOccupancy()
        == other.getLocalOccupancy());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrtime());
    hash = (37 * hash) + LOCALOCCUPANCY_FIELD_NUMBER;
    hash = (53 * hash) + getLocalOccupancy();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyLevel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.occupancy.OccupancyLevel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.occupancy.OccupancyLevel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.occupancy.OccupancyLevel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code occupancy.OccupancyLevel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:occupancy.OccupancyLevel)
      grpc.services.occupancy.OccupancyLevelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyLevel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.occupancy.OccupancyLevel.class, grpc.services.occupancy.OccupancyLevel.Builder.class);
    }

    // Construct using grpc.services.occupancy.OccupancyLevel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currtime_ = 0L;

      localOccupancy_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyLevel_descriptor;
    }

    @java.lang.Override
    public grpc.services.occupancy.OccupancyLevel getDefaultInstanceForType() {
      return grpc.services.occupancy.OccupancyLevel.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.occupancy.OccupancyLevel build() {
      grpc.services.occupancy.OccupancyLevel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.occupancy.OccupancyLevel buildPartial() {
      grpc.services.occupancy.OccupancyLevel result = new grpc.services.occupancy.OccupancyLevel(this);
      result.currtime_ = currtime_;
      result.localOccupancy_ = localOccupancy_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.occupancy.OccupancyLevel) {
        return mergeFrom((grpc.services.occupancy.OccupancyLevel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.occupancy.OccupancyLevel other) {
      if (other == grpc.services.occupancy.OccupancyLevel.getDefaultInstance()) return this;
      if (other.getCurrtime() != 0L) {
        setCurrtime(other.getCurrtime());
      }
      if (other.getLocalOccupancy() != 0) {
        setLocalOccupancy(other.getLocalOccupancy());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.occupancy.OccupancyLevel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.occupancy.OccupancyLevel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long currtime_ ;
    /**
     * <code>int64 currtime = 1;</code>
     */
    public long getCurrtime() {
      return currtime_;
    }
    /**
     * <code>int64 currtime = 1;</code>
     */
    public Builder setCurrtime(long value) {
      
      currtime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 currtime = 1;</code>
     */
    public Builder clearCurrtime() {
      
      currtime_ = 0L;
      onChanged();
      return this;
    }

    private int localOccupancy_ ;
    /**
     * <code>int32 localOccupancy = 2;</code>
     */
    public int getLocalOccupancy() {
      return localOccupancy_;
    }
    /**
     * <code>int32 localOccupancy = 2;</code>
     */
    public Builder setLocalOccupancy(int value) {
      
      localOccupancy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 localOccupancy = 2;</code>
     */
    public Builder clearLocalOccupancy() {
      
      localOccupancy_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:occupancy.OccupancyLevel)
  }

  // @@protoc_insertion_point(class_scope:occupancy.OccupancyLevel)
  private static final grpc.services.occupancy.OccupancyLevel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.occupancy.OccupancyLevel();
  }

  public static grpc.services.occupancy.OccupancyLevel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OccupancyLevel>
      PARSER = new com.google.protobuf.AbstractParser<OccupancyLevel>() {
    @java.lang.Override
    public OccupancyLevel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OccupancyLevel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OccupancyLevel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OccupancyLevel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.occupancy.OccupancyLevel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

