// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package grpc.services.light;

public interface IntensityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Light.IntensityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intensity = 1;</code>
   */
  int getIntensity();
}
