// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package grpc.services.light;

public interface LightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Light.LightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
