// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package grpc.services.light;

public final class LightServiceImpl {
  private LightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Light_LightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Light_LightingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Light_LightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Light_LightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Light_LightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Light_LightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Light_IntensityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Light_IntensityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Light_IntensityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Light_IntensityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Light_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Light_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LightService.proto\022\005Light\"F\n\020LightingR" +
      "esponse\022\017\n\007lightId\030\001 \001(\t\022\016\n\006status\030\002 \001(\t" +
      "\022\021\n\tintensity\030\003 \001(\005\"\037\n\rLightsRequest\022\016\n\006" +
      "switch\030\001 \001(\010\" \n\016LightsResponse\022\016\n\006switch" +
      "\030\001 \001(\010\"&\n\021IntensityResponse\022\021\n\tintensity" +
      "\030\001 \001(\005\"%\n\020IntensityRequest\022\021\n\tintensity\030" +
      "\001 \001(\005\"\007\n\005Empty2\312\001\n\014LightService\0223\n\010light" +
      "ing\022\014.Light.Empty\032\027.Light.LightingRespon" +
      "se\"\000\022<\n\013LightsOnOff\022\024.Light.LightsReques" +
      "t\032\025.Light.LightsResponse\"\000\022G\n\016lightInten" +
      "sity\022\027.Light.IntensityRequest\032\030.Light.In" +
      "tensityResponse\"\000(\001B)\n\023grpc.services.lig" +
      "htB\020LightServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Light_LightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Light_LightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Light_LightingResponse_descriptor,
        new java.lang.String[] { "LightId", "Status", "Intensity", });
    internal_static_Light_LightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Light_LightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Light_LightsRequest_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_Light_LightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Light_LightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Light_LightsResponse_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_Light_IntensityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Light_IntensityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Light_IntensityResponse_descriptor,
        new java.lang.String[] { "Intensity", });
    internal_static_Light_IntensityRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Light_IntensityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Light_IntensityRequest_descriptor,
        new java.lang.String[] { "Intensity", });
    internal_static_Light_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Light_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Light_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
