// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.services.energy;

public final class EnergyServiceImpl {
  private EnergyServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_DevicesOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energy_DevicesOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_DevicesOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energy_DevicesOffResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_Lights_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energy_Lights_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_LightsOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energy_LightsOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_LightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energy_LightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energy_LightAdjustRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energy_LightAdjustRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026energyEfficiency.proto\022\006energy\"&\n\021Devi" +
      "cesOffRequest\022\021\n\tdeviceOff\030\001 \001(\010\"\'\n\022Devi" +
      "cesOffResponse\022\021\n\tdeviceOff\030\001 \001(\010\">\n\006Lig" +
      "hts\022\017\n\007lightId\030\001 \001(\005\022\023\n\013lightStatus\030\002 \001(" +
      "\t\022\016\n\006adjust\030\003 \001(\005\"\"\n\017LightsOnRequest\022\017\n\007" +
      "lightId\030\001 \001(\005\"/\n\016LightsResponse\022\035\n\005light" +
      "\030\001 \001(\0132\016.energy.Lights\"5\n\022LightAdjustReq" +
      "uest\022\017\n\007lightId\030\001 \001(\005\022\016\n\006adjust\030\002 \001(\0052\350\001" +
      "\n\rEnergyService\022H\n\rswitchDevices\022\031.energ" +
      "y.DevicesOffRequest\032\032.energy.DevicesOffR" +
      "esponse\"\000\022C\n\016switchLightsOn\022\027.energy.Lig" +
      "htsOnRequest\032\026.energy.LightsResponse\"\000\022H" +
      "\n\016lightIntensity\022\032.energy.LightAdjustReq" +
      "uest\032\026.energy.LightsResponse\"\000(\001B+\n\024grpc" +
      ".services.energyB\021EnergyServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_energy_DevicesOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_energy_DevicesOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energy_DevicesOffRequest_descriptor,
        new java.lang.String[] { "DeviceOff", });
    internal_static_energy_DevicesOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_energy_DevicesOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energy_DevicesOffResponse_descriptor,
        new java.lang.String[] { "DeviceOff", });
    internal_static_energy_Lights_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_energy_Lights_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energy_Lights_descriptor,
        new java.lang.String[] { "LightId", "LightStatus", "Adjust", });
    internal_static_energy_LightsOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_energy_LightsOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energy_LightsOnRequest_descriptor,
        new java.lang.String[] { "LightId", });
    internal_static_energy_LightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_energy_LightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energy_LightsResponse_descriptor,
        new java.lang.String[] { "Light", });
    internal_static_energy_LightAdjustRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_energy_LightAdjustRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energy_LightAdjustRequest_descriptor,
        new java.lang.String[] { "LightId", "Adjust", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
