// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.services.energy;

public interface LightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.LightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.energy.Lights light = 1;</code>
   */
  boolean hasLight();
  /**
   * <code>.energy.Lights light = 1;</code>
   */
  grpc.services.energy.Lights getLight();
  /**
   * <code>.energy.Lights light = 1;</code>
   */
  grpc.services.energy.LightsOrBuilder getLightOrBuilder();
}
