// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energyEfficiency.proto

package grpc.services.energy;

public interface LightsSwitchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energy.LightsSwitchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightId = 1;</code>
   */
  int getLightId();
}
