// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OccupancyService.proto

package grpc.services.occupancy;

public interface CameraSwitchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.CameraSwitchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool cameraOn = 1;</code>
   */
  boolean getCameraOn();
}
