// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OccupancyService.proto

package grpc.services.occupancy;

public interface FindListDayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.FindListDay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string day = 1;</code>
   */
  java.lang.String getDay();
  /**
   * <code>string day = 1;</code>
   */
  com.google.protobuf.ByteString
      getDayBytes();
}
