// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OccupancyService.proto

package grpc.services.occupancy;

public interface OccupancyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.OccupancyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.occupancy.Occupancy occupancy = 2;</code>
   */
  boolean hasOccupancy();
  /**
   * <code>.occupancy.Occupancy occupancy = 2;</code>
   */
  grpc.services.occupancy.Occupancy getOccupancy();
  /**
   * <code>.occupancy.Occupancy occupancy = 2;</code>
   */
  grpc.services.occupancy.OccupancyOrBuilder getOccupancyOrBuilder();
}
