// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OccupancyService.proto

package grpc.services.occupancy;

/**
 * Protobuf type {@code occupancy.OccupancyResponse}
 */
public  final class OccupancyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:occupancy.OccupancyResponse)
    OccupancyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OccupancyResponse.newBuilder() to construct.
  private OccupancyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OccupancyResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OccupancyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            grpc.services.occupancy.Occupancy.Builder subBuilder = null;
            if (occupancy_ != null) {
              subBuilder = occupancy_.toBuilder();
            }
            occupancy_ = input.readMessage(grpc.services.occupancy.Occupancy.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(occupancy_);
              occupancy_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.occupancy.OccupancyResponse.class, grpc.services.occupancy.OccupancyResponse.Builder.class);
  }

  public static final int OCCUPANCY_FIELD_NUMBER = 2;
  private grpc.services.occupancy.Occupancy occupancy_;
  /**
   * <code>.occupancy.Occupancy occupancy = 2;</code>
   */
  public boolean hasOccupancy() {
    return occupancy_ != null;
  }
  /**
   * <code>.occupancy.Occupancy occupancy = 2;</code>
   */
  public grpc.services.occupancy.Occupancy getOccupancy() {
    return occupancy_ == null ? grpc.services.occupancy.Occupancy.getDefaultInstance() : occupancy_;
  }
  /**
   * <code>.occupancy.Occupancy occupancy = 2;</code>
   */
  public grpc.services.occupancy.OccupancyOrBuilder getOccupancyOrBuilder() {
    return getOccupancy();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (occupancy_ != null) {
      output.writeMessage(2, getOccupancy());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (occupancy_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOccupancy());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.occupancy.OccupancyResponse)) {
      return super.equals(obj);
    }
    grpc.services.occupancy.OccupancyResponse other = (grpc.services.occupancy.OccupancyResponse) obj;

    boolean result = true;
    result = result && (hasOccupancy() == other.hasOccupancy());
    if (hasOccupancy()) {
      result = result && getOccupancy()
          .equals(other.getOccupancy());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOccupancy()) {
      hash = (37 * hash) + OCCUPANCY_FIELD_NUMBER;
      hash = (53 * hash) + getOccupancy().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.occupancy.OccupancyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.occupancy.OccupancyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.occupancy.OccupancyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code occupancy.OccupancyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:occupancy.OccupancyResponse)
      grpc.services.occupancy.OccupancyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.occupancy.OccupancyResponse.class, grpc.services.occupancy.OccupancyResponse.Builder.class);
    }

    // Construct using grpc.services.occupancy.OccupancyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (occupancyBuilder_ == null) {
        occupancy_ = null;
      } else {
        occupancy_ = null;
        occupancyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.occupancy.OccupancyServiceImpl.internal_static_occupancy_OccupancyResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.occupancy.OccupancyResponse getDefaultInstanceForType() {
      return grpc.services.occupancy.OccupancyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.occupancy.OccupancyResponse build() {
      grpc.services.occupancy.OccupancyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.occupancy.OccupancyResponse buildPartial() {
      grpc.services.occupancy.OccupancyResponse result = new grpc.services.occupancy.OccupancyResponse(this);
      if (occupancyBuilder_ == null) {
        result.occupancy_ = occupancy_;
      } else {
        result.occupancy_ = occupancyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.occupancy.OccupancyResponse) {
        return mergeFrom((grpc.services.occupancy.OccupancyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.occupancy.OccupancyResponse other) {
      if (other == grpc.services.occupancy.OccupancyResponse.getDefaultInstance()) return this;
      if (other.hasOccupancy()) {
        mergeOccupancy(other.getOccupancy());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.occupancy.OccupancyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.occupancy.OccupancyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.services.occupancy.Occupancy occupancy_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.occupancy.Occupancy, grpc.services.occupancy.Occupancy.Builder, grpc.services.occupancy.OccupancyOrBuilder> occupancyBuilder_;
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public boolean hasOccupancy() {
      return occupancyBuilder_ != null || occupancy_ != null;
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public grpc.services.occupancy.Occupancy getOccupancy() {
      if (occupancyBuilder_ == null) {
        return occupancy_ == null ? grpc.services.occupancy.Occupancy.getDefaultInstance() : occupancy_;
      } else {
        return occupancyBuilder_.getMessage();
      }
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public Builder setOccupancy(grpc.services.occupancy.Occupancy value) {
      if (occupancyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        occupancy_ = value;
        onChanged();
      } else {
        occupancyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public Builder setOccupancy(
        grpc.services.occupancy.Occupancy.Builder builderForValue) {
      if (occupancyBuilder_ == null) {
        occupancy_ = builderForValue.build();
        onChanged();
      } else {
        occupancyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public Builder mergeOccupancy(grpc.services.occupancy.Occupancy value) {
      if (occupancyBuilder_ == null) {
        if (occupancy_ != null) {
          occupancy_ =
            grpc.services.occupancy.Occupancy.newBuilder(occupancy_).mergeFrom(value).buildPartial();
        } else {
          occupancy_ = value;
        }
        onChanged();
      } else {
        occupancyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public Builder clearOccupancy() {
      if (occupancyBuilder_ == null) {
        occupancy_ = null;
        onChanged();
      } else {
        occupancy_ = null;
        occupancyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public grpc.services.occupancy.Occupancy.Builder getOccupancyBuilder() {
      
      onChanged();
      return getOccupancyFieldBuilder().getBuilder();
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    public grpc.services.occupancy.OccupancyOrBuilder getOccupancyOrBuilder() {
      if (occupancyBuilder_ != null) {
        return occupancyBuilder_.getMessageOrBuilder();
      } else {
        return occupancy_ == null ?
            grpc.services.occupancy.Occupancy.getDefaultInstance() : occupancy_;
      }
    }
    /**
     * <code>.occupancy.Occupancy occupancy = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.occupancy.Occupancy, grpc.services.occupancy.Occupancy.Builder, grpc.services.occupancy.OccupancyOrBuilder> 
        getOccupancyFieldBuilder() {
      if (occupancyBuilder_ == null) {
        occupancyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.services.occupancy.Occupancy, grpc.services.occupancy.Occupancy.Builder, grpc.services.occupancy.OccupancyOrBuilder>(
                getOccupancy(),
                getParentForChildren(),
                isClean());
        occupancy_ = null;
      }
      return occupancyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:occupancy.OccupancyResponse)
  }

  // @@protoc_insertion_point(class_scope:occupancy.OccupancyResponse)
  private static final grpc.services.occupancy.OccupancyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.occupancy.OccupancyResponse();
  }

  public static grpc.services.occupancy.OccupancyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OccupancyResponse>
      PARSER = new com.google.protobuf.AbstractParser<OccupancyResponse>() {
    @java.lang.Override
    public OccupancyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OccupancyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OccupancyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OccupancyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.occupancy.OccupancyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

