// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OccupancyService.proto

package grpc.services.occupancy;

public interface OccupancyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.Occupancy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room = 1;</code>
   */
  java.lang.String getRoom();
  /**
   * <code>string room = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomBytes();

  /**
   * <code>int32 localOccupancy = 2;</code>
   */
  int getLocalOccupancy();
}
