// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OccupancyService.proto

package grpc.services.occupancy;

public final class OccupancyServiceImpl {
  private OccupancyServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_LocalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_LocalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_OccupancyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_OccupancyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_CameraSwitchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_CameraSwitchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_CameraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_CameraResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_FindListDay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_FindListDay_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_ListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026OccupancyService.proto\022\toccupancy\"\034\n\014L" +
      "ocalRequest\022\014\n\004room\030\001 \001(\t\"9\n\021OccupancyRe" +
      "sponse\022\014\n\004room\030\001 \001(\t\022\026\n\016localOccupancy\030\002" +
      " \001(\005\"\'\n\023CameraSwitchRequest\022\020\n\010cameraOn\030" +
      "\001 \001(\010\"\"\n\016CameraResponse\022\020\n\010cameraOn\030\001 \001(" +
      "\010\"\032\n\013FindListDay\022\013\n\003day\030\001 \001(\t\")\n\014ListRes" +
      "ponse\022\013\n\003day\030\001 \001(\t\022\014\n\004list\030\002 \001(\t2\361\001\n\020Occ" +
      "upancyService\022G\n\014getOccupancy\022\027.occupanc" +
      "y.LocalRequest\032\034.occupancy.OccupancyResp" +
      "onse\"\000\022M\n\016switchCameraOn\022\036.occupancy.Cam" +
      "eraSwitchRequest\032\031.occupancy.CameraRespo" +
      "nse\"\000\022E\n\014getVisitList\022\026.occupancy.FindLi" +
      "stDay\032\027.occupancy.ListResponse\"\000(\0010\001B1\n\027" +
      "grpc.services.occupancyB\024OccupancyServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_occupancy_LocalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_occupancy_LocalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_LocalRequest_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_occupancy_OccupancyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_occupancy_OccupancyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_OccupancyResponse_descriptor,
        new java.lang.String[] { "Room", "LocalOccupancy", });
    internal_static_occupancy_CameraSwitchRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_occupancy_CameraSwitchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_CameraSwitchRequest_descriptor,
        new java.lang.String[] { "CameraOn", });
    internal_static_occupancy_CameraResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_occupancy_CameraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_CameraResponse_descriptor,
        new java.lang.String[] { "CameraOn", });
    internal_static_occupancy_FindListDay_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_occupancy_FindListDay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_FindListDay_descriptor,
        new java.lang.String[] { "Day", });
    internal_static_occupancy_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_occupancy_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_ListResponse_descriptor,
        new java.lang.String[] { "Day", "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
