// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateService.proto

package grpc.services.climate;

public interface CoLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Climate.CoLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 level = 1;</code>
   */
  int getLevel();
}
