// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateService.proto

package grpc.services.climate;

/**
 * Protobuf type {@code climate.HvacResponse}
 */
public  final class HvacResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:climate.HvacResponse)
    HvacResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HvacResponse.newBuilder() to construct.
  private HvacResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HvacResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HvacResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.services.climate.Hvac.Builder subBuilder = null;
            if (hvac_ != null) {
              subBuilder = hvac_.toBuilder();
            }
            hvac_ = input.readMessage(grpc.services.climate.Hvac.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hvac_);
              hvac_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.climate.ClimateServiceImpl.internal_static_climate_HvacResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.climate.ClimateServiceImpl.internal_static_climate_HvacResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.climate.HvacResponse.class, grpc.services.climate.HvacResponse.Builder.class);
  }

  public static final int HVAC_FIELD_NUMBER = 1;
  private grpc.services.climate.Hvac hvac_;
  /**
   * <code>.climate.Hvac hvac = 1;</code>
   */
  public boolean hasHvac() {
    return hvac_ != null;
  }
  /**
   * <code>.climate.Hvac hvac = 1;</code>
   */
  public grpc.services.climate.Hvac getHvac() {
    return hvac_ == null ? grpc.services.climate.Hvac.getDefaultInstance() : hvac_;
  }
  /**
   * <code>.climate.Hvac hvac = 1;</code>
   */
  public grpc.services.climate.HvacOrBuilder getHvacOrBuilder() {
    return getHvac();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hvac_ != null) {
      output.writeMessage(1, getHvac());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hvac_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHvac());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.climate.HvacResponse)) {
      return super.equals(obj);
    }
    grpc.services.climate.HvacResponse other = (grpc.services.climate.HvacResponse) obj;

    boolean result = true;
    result = result && (hasHvac() == other.hasHvac());
    if (hasHvac()) {
      result = result && getHvac()
          .equals(other.getHvac());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHvac()) {
      hash = (37 * hash) + HVAC_FIELD_NUMBER;
      hash = (53 * hash) + getHvac().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.climate.HvacResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.climate.HvacResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.climate.HvacResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.climate.HvacResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.climate.HvacResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.climate.HvacResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.climate.HvacResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.climate.HvacResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.climate.HvacResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.climate.HvacResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.climate.HvacResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.climate.HvacResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.climate.HvacResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code climate.HvacResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:climate.HvacResponse)
      grpc.services.climate.HvacResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.climate.ClimateServiceImpl.internal_static_climate_HvacResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.climate.ClimateServiceImpl.internal_static_climate_HvacResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.climate.HvacResponse.class, grpc.services.climate.HvacResponse.Builder.class);
    }

    // Construct using grpc.services.climate.HvacResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (hvacBuilder_ == null) {
        hvac_ = null;
      } else {
        hvac_ = null;
        hvacBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.climate.ClimateServiceImpl.internal_static_climate_HvacResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.climate.HvacResponse getDefaultInstanceForType() {
      return grpc.services.climate.HvacResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.climate.HvacResponse build() {
      grpc.services.climate.HvacResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.climate.HvacResponse buildPartial() {
      grpc.services.climate.HvacResponse result = new grpc.services.climate.HvacResponse(this);
      if (hvacBuilder_ == null) {
        result.hvac_ = hvac_;
      } else {
        result.hvac_ = hvacBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.climate.HvacResponse) {
        return mergeFrom((grpc.services.climate.HvacResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.climate.HvacResponse other) {
      if (other == grpc.services.climate.HvacResponse.getDefaultInstance()) return this;
      if (other.hasHvac()) {
        mergeHvac(other.getHvac());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.climate.HvacResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.climate.HvacResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.services.climate.Hvac hvac_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.climate.Hvac, grpc.services.climate.Hvac.Builder, grpc.services.climate.HvacOrBuilder> hvacBuilder_;
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public boolean hasHvac() {
      return hvacBuilder_ != null || hvac_ != null;
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public grpc.services.climate.Hvac getHvac() {
      if (hvacBuilder_ == null) {
        return hvac_ == null ? grpc.services.climate.Hvac.getDefaultInstance() : hvac_;
      } else {
        return hvacBuilder_.getMessage();
      }
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public Builder setHvac(grpc.services.climate.Hvac value) {
      if (hvacBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hvac_ = value;
        onChanged();
      } else {
        hvacBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public Builder setHvac(
        grpc.services.climate.Hvac.Builder builderForValue) {
      if (hvacBuilder_ == null) {
        hvac_ = builderForValue.build();
        onChanged();
      } else {
        hvacBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public Builder mergeHvac(grpc.services.climate.Hvac value) {
      if (hvacBuilder_ == null) {
        if (hvac_ != null) {
          hvac_ =
            grpc.services.climate.Hvac.newBuilder(hvac_).mergeFrom(value).buildPartial();
        } else {
          hvac_ = value;
        }
        onChanged();
      } else {
        hvacBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public Builder clearHvac() {
      if (hvacBuilder_ == null) {
        hvac_ = null;
        onChanged();
      } else {
        hvac_ = null;
        hvacBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public grpc.services.climate.Hvac.Builder getHvacBuilder() {
      
      onChanged();
      return getHvacFieldBuilder().getBuilder();
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    public grpc.services.climate.HvacOrBuilder getHvacOrBuilder() {
      if (hvacBuilder_ != null) {
        return hvacBuilder_.getMessageOrBuilder();
      } else {
        return hvac_ == null ?
            grpc.services.climate.Hvac.getDefaultInstance() : hvac_;
      }
    }
    /**
     * <code>.climate.Hvac hvac = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.climate.Hvac, grpc.services.climate.Hvac.Builder, grpc.services.climate.HvacOrBuilder> 
        getHvacFieldBuilder() {
      if (hvacBuilder_ == null) {
        hvacBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.services.climate.Hvac, grpc.services.climate.Hvac.Builder, grpc.services.climate.HvacOrBuilder>(
                getHvac(),
                getParentForChildren(),
                isClean());
        hvac_ = null;
      }
      return hvacBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:climate.HvacResponse)
  }

  // @@protoc_insertion_point(class_scope:climate.HvacResponse)
  private static final grpc.services.climate.HvacResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.climate.HvacResponse();
  }

  public static grpc.services.climate.HvacResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HvacResponse>
      PARSER = new com.google.protobuf.AbstractParser<HvacResponse>() {
    @java.lang.Override
    public HvacResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HvacResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HvacResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HvacResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.climate.HvacResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

