// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateService.proto

package grpc.services.climate;

public interface HvacRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Climate.HvacRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp = 1;</code>
   */
  int getTemp();
}
