// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateService.proto

package grpc.services.climate;

public interface SwitchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Climate.SwitchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool power = 1;</code>
   */
  boolean getPower();
}
