// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: climateControl.proto

package services.climate;

public interface HVACStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:climate.HVACStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 HVACId = 1;</code>
   */
  int getHVACId();
}
