// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: climateControl.proto

package services.climate;

public interface HVACStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:climate.HVACStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
